name: Perform static analysis on Python files

on:
  pull_request:
    paths:
      - '*.py'
      - '.isort.cfg'
      - 'setup.cfg'

jobs:
  autoformat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - run: |
        pip install poetry
        poetry config virtualenvs.in-project true
        poetry install --no-root
    - run: poetry run isort --check --diff hy tests
    - run: poetry run black --check --diff hy tests
